### ISSUE TITLE
Report explicit use of default value

### ISSUE THREAD

**Issue by ijcd** [ansible/ansible-lint#122]
# Issue Type
- Feature request
# Desired Behaviour

It would be nice if ansible-lint could report when a default value is specified explicitly. Then they could be removed to clean up clutter.

**Comment by willthames** [comment]
ansible-lint doesn't do much interpretation of variables at all at the moment (because it doesn't know, and it shouldn't be important, what host the playbook will be run against, it can't populate the variables).

Do you have a particular, non host example in mind - we won't be able to do much if a host gets a variable from a group that is the same as the default.

**Comment by ssbarnea** [comment]
Outside the scope of the linter and also almost impossible to implement, due to the various number of places where variables can be defined.
