### ISSUE TITLE
It's not possible to install ansible-lint 6.9.0 using poetry

### ISSUE THREAD

**Issue by xfix** [ansible/ansible-lint#2730]
##### Summary

Installing ansible-lint using `poetry add ansible-lint@latest` is not possible.

##### Issue Type

- Bug Report

##### STEPS TO REPRODUCE

Create a new project with `poetry init` and then run `poetry add ansible-lint@latest`

##### Desired Behavior

`ansible-lint` should be installed.

##### Actual Behavior

```
$ poetry add ansible-lint@latest
Using version ^6.9.0 for ansible-lint

Updating dependencies
Resolving dependencies... (0.1s)

Because no versions of ansible-lint match >6.9.0,<7.0.0
 and ansible-lint (6.9.0) depends on will-not-work-on-windows-try-from-wsl-instead (*), ansible-lint (>=6.9.0,<7.0.0) requires will-not-work-on-windows-try-from-wsl-instead (*).
So, because no versions of will-not-work-on-windows-try-from-wsl-instead match *
 and project depends on ansible-lint (>=6.9.0,<7.0.0), version solving failed.
```

**Comment by ssbarnea** [comment]
Sorry but this is a bug of poetry, not ansible-lint. Our dependencies are declared like this on purpose.

See https://github.com/ansible/ansible-lint/blob/main/setup.cfg#L74

**Comment by finswimmer** [comment]
Hello @ssbarnea,

unfortunately defining a non-existing dependency for a specific platform is problematic in multiple cases:

- Any tool that is doing a universal locking like Poetry or PDM will raise an error because it cannot find this dependency. Universal locking means, that the dependency resolution is done independently of the current platform and Python version, by only looking at the constraints. Thus the lock file can be used with any Python version that the project aims to be compatible.
- Someone can register this non-existing dependency and suddenly this is pulled into the environment. That's a potential security issue.

The hint in the [documentation](https://ansible-lint.readthedocs.io/installing/) about the fact, that `ansible-lint` cannot be installed on Windows, should be sufficient. Maybe put it into the README of this repo as well?

Best regards,
fin swimmer

**Comment by xfix** [comment]
For reference for anyone who finds this ticket, this issue can be workarounded by using `markers`:

```toml
ansible-lint = { version = "^6.9.0", markers = "platform_system != 'Windows'" }
```

**Comment by ssbarnea** [comment]
@finswimmer pip-tools compile does not suffer from the same limitations, we use it without problems. You cannot expect that all the dependencies to be always available and I am sure that there are other packages on pypi with similar issues.

@xfix Thanks for providing a workaround. Feel free to make a PR to add a section for poetry in installation section, so others might find your valuable workaround.

**Comment by xfix** [comment]
My personal opinion is that ansible-lint abuses the requirements system, and this work-around is non-ideal because it would break if ansible-lint were to add a similar hack for some other platform.
