### ISSUE TITLE
args: ImportError('attempted relative import with no known parent package')

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#2805]
I discovered that our newly args module is something throwing some weird Import Errors, and this time I found the culprit is ansible-core, which for some very weird reasons was using a relative import in the cose, which is a known issue.

https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/rules/args.py#L88

Replacing the relative import with a full import sorted the issue. Clearly we need to sort this in core and introduce a measure for preventing use of relative imports in the future.

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/setup.py#L175

One pleasant surprise is that this is the only relative import from lib, there are others inside tests but on code that ships, that is the only one.

**Comment by webknjaz** [comment]
The problem is that the low-level machinery is used and it does not specify `ansible` as a top-level package so the loader assumes that what you're importing must be top-level already.
Higher-level functions like `import_module()` or `find_spec()` have a `package` argument for specifying what is top-level. If you want to keep using the low-level API, you'll need to find a way to specify where the top-level package is too.
