### ISSUE TITLE
Mechanism to manage rulesets

### ISSUE THREAD

**Issue by techzilla** [ansible/ansible-lint#310]
# Issue Type
- Feature request

# Desired Behaviour

We need a mechanism to properly manage rulesets, would it somehow be possible to install ansible-lint, and then install an additional package of rules via Pip?

**Comment by techzilla** [comment]
Looks like this would require something like a plugin framework, most especially since rules are actually class's. IE, like pylint.  Unless a simpler concept exists I haven't considered.

**Comment by ssbarnea** [comment]
I am going to close this because currently you can already have custom rules inside your repository and if nobody proposed a plugin system, I doubt we will see it implemented.

Note: I am not against a plugin system. If you really want to make a PR that makes use of pluggy or similar, we will consider it.
