### ISSUE TITLE
Misreports a list of ints variable as <class 'str'>

### ISSUE THREAD

**Issue by bradleyfrank** [ansible/ansible-lint#4229]
##### Summary

The `community.general.mas` module takes a [int or list](https://docs.ansible.com/ansible/latest/collections/community/general/mas_module.html#parameter-id) for the parameter `id`. When given a variable that is a list of ints, `ansible-lint` reports that the variable is of type `<class 'str'>`.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 24.6.1 using ansible-core:2.16.7 ansible-compat:24.6.0 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
```

```console
% sw_vers
ProductName:            macOS
ProductVersion:         14.4.1
BuildVersion:           23E224

% ansible --version
ansible [core 2.16.7]
  config file = ~/.../ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.../ansible
  ansible collection location = ~/.ansible/collections
  executable location = ~/.../ansible
  python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (~/.../python)
  jinja version = 3.1.4
  libyaml = True
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Run `ansible-playbook` with this example task:

```console (paste below)
- name: "Install apps via mas"
  vars:
    ids:
      - 1516894961
      - 1555925018
  community.general.mas:
    id: "{{ ids }}"
```

##### Desired Behavior

No warning, the variable is of type list, elements are ints.

##### Actual Behavior

```paste below
% ansible-lint roles/pkgs/tasks/pkg_mgr/mas.yml
WARNING  Listing 1 violation(s) that are fatal
args[module]: Elements value for option 'id' is of type <class 'str'> and we were unable to convert to int: <class 'str'> cannot be converted to an int (warning)
roles/pkgs/tasks/pkg_mgr/mas.yml:8 Task/Handler: Install apps via mas

Read documentation for instructions on how to ignore specific rule violations.

                  Rule Violation Summary
 count tag          profile rule associated tags
     1 args[module]         syntax, experimental (warning)
```

**Comment by johnbyrneio** [comment]
I ran into the same issue today. 

The cause is [here](https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/rules/args.py#L228).

When type checking a module parameter fails, the error message returned is:
`argument '<module_parameter>' is of type <class 'str'>`

But when the expected type is a list, the element type is also checked, which returns a different error message:
`Elements value for option '<module_parameter>' is of type <class 'str'>'

Changing the regexp from:
`r"argument '(?P<name>.*)' is of type",`
to
`r"(argument|option) '(?P<name>.*)' is of type",`
resolves the issue.

**Comment by johnbyrneio** [comment]
Submitted #4279 to fix this.
