### ISSUE TITLE
Replace deprecate optparse with more modern implementation

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#730]
I would like to replace the outdated optparse with a more modern library. The official replacement from stdlibis argparse but I would like to use the opportunity to evaluate if it would not make sense to use something even more advanced.

* `argparse` - stdlib, no extra dependencies, already an existing https://github.com/ansible/ansible-lint/pull/645/files (needs rebase, hopefully author still has interested)
* [click](https://pypi.org/project/click/) (BSD) - very powerful, extensible with plugins, already used by molecule, actively maintained (after a gap in 2019).(9k★)
* [docopt](https://pypi.org/project/docopt/#history) - ruled out, dead.
* [fire](https://pypi.org/project/fire/) - a popular google backed project, but this also makes it a potential liability. (16k★)

References:
* http://xion.io/post/programming/python-dont-use-click.html - seems "bit" biased but worth the read 

@awcrosby @webknjaz Any preferences? I was originally aiming to support click but after reading more and considering that we are talking only about a linter, probably argparse would be the best bet.

**Comment by webknjaz** [comment]
> * [docopt](https://pypi.org/project/docopt/#history) - ruled out, dead.

:-1: Agreed. It's also controversial because some definitions are done "outside of the code" which makes understanding how things work hard and the contribution barrier is high (I was changing a project that uses it a long time ago and I recall it took me some time to figure out where and how to properly stick new options there).


> * [fire](https://pypi.org/project/fire/) - a popular google backed project, but this also makes it a potential liability. (16k★)

I think I've heard of it but didn't like the interface. No strong feelings (except for the Google's influence). I wouldn't use it if I personally were to implement the thing.


> * [click](https://pypi.org/project/click/) (BSD) - very powerful, extensible with plugins, already used by molecule, actively maintained (after a gap in 2019).(9k★)

Among those I used myself, I think I liked click most. Pallets recently got a grant from the PSF+Tidelift (I think) and David (the maintainer) is a nice fella.


There's also [typer](https://typer.tiangolo.com/) from Sebastián Ramírez who I've met a few months ago at a conference (also a great person). It uses click under the hood but also **fully** relies on type hints. Using it would mean dropping support for Python 3.5, though, because it requires Python 3.6+.


> * `argparse` - stdlib, no extra dependencies, already an existing [#645 (files)](https://github.com/ansible/ansible-lint/pull/645/files) (needs rebase, hopefully author still has interested)

I like this option because (1) it's a no deps solution and also (2) the author has spent a great effort refactoring it and did a great job. As for rebasing, we can do it if necessary, it's not a problem. Somebody can even just take that branch and re-submit as a separate PR.
