### ISSUE TITLE
[HELP WANTED] [SEND PR] Recover calling `get_playbooks_and_roles`

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#731]
# Issue Type
- Bug report

# What's up?

While updating #645, I noticed that [the call to `get_playbooks_and_roles()` got removed](https://github.com/ansible/ansible-lint/pull/573/files#diff-e5d3af2dcf25a4d665f0ef298f146a85L154) and it seems like now it's not called from anywhere. It needs to be recovered. I guess it should go to `get_config()` in the `cli` module.

**Comment by webknjaz** [comment]
@ssbarnea ^

**Comment by webknjaz** [comment]
@cans did you forget to send https://github.com/cans/ansible-lint/commit/305883f7466ae452b4ea723a3fab2d105c211a74 as a PR?

**Comment by cans** [comment]
I did not forget. Working on it. But I saw #645 was changing the `get_config()` function API. So I was waiting for it to be merged (which is now done). And it also needs some regression tests so that does not happen again.

There is also the fact that the `get_playbooks_and_roles()` does not return absolute path. I'd like to fix that, but as mentioned in #744, that function seem a bit "touchy". There are a few trick we can use to quickly decrease that. Also would you mind if the function became a private function in the `cli` module, probably alongside with the `get_yaml_files()` function. They are not used anywhere else. Not sure if the latter could be ?

The id is, as you suggested above, is that the `ansiblelint.cli.get_config()` functions returns all configuration. The main function only has to act on it.

Hopefully a first "draft" will come before end of day.

**Comment by webknjaz** [comment]
Great, thanks! Sounds good.

The reason I was asking, is because I saw a backreference in this issue from the commit and it's usually a good idea to somehow indicate in the issue that somebody is working on it to avoid "race conditions". Also, commit references to issues don't generate any notifications so I only noticed it accidentally because I opened the issue.

**Comment by webknjaz** [comment]
Fixed by https://github.com/ansible/ansible-lint/pull/767.
