### ISSUE TITLE
ansible-lint throws "701 No 'galaxy_info' found" error when the dependency is set to local role

### ISSUE THREAD

**Issue by fartosh** [ansible/ansible-lint#818]
##### Summary

Running ansible-lint against the role that has local role dependency, it throws "701 No 'galaxy_info' found". An exception should be made for this kind of dependencies as there will be no galaxy_info for my local roles.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
---
ansible 2.9.9
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

ansible-lint --version
---
ansible-lint 4.2.0
```

- ansible installation method: one of source, pip, OS package
pip
- ansible-lint installation method: one of source, pip, OS package
pip

##### STEPS TO REPRODUCE

1. Create the role foo
2. Create the role bar with `meta/main.yml` file:
```
dependencies:
  - foo
```
3. Run ansible-lint

##### Desired Behaviour

There is no "701 No 'galaxy_info' found" error in the output

##### Actual Behaviour

```
701 No 'galaxy_info' found
[...]/roles/bar/meta/main.yml:4
{'meta/main.yml': {'skipped_rules': [], '__file__': u'[...]/roles/bar/meta/main.yml', u'dependencies': [{'__file__': u'[...]/roles/bar/meta/main.yml', u'role': u'foo', '__line__': 5}], '__line__': 4}}
```

**Comment by ssbarnea** [comment]
I don't see the bug here, all the roles must have meta.

Have also tried with code from master branch like requested on bug form?

**Comment by fartosh** [comment]
All the roles **could** have meta, ours don't :) We create our custom roles manually, not via `ansible-galaxy` so it is not necessary for us to have meta info in every role. That's why I consider failing the whole test a bit too strict in this case. Also, [Ansible docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html) don't mention having `meta` directory as a best-practice.

**Comment by ssbarnea** [comment]
Documentation is clear about how to add rules to skiplist, see https://docs.ansible.com/ansible-lint/configuring/configuring.html#configuration-file

@webknjaz Ok to close, i think.

**Comment by rascasoft** [comment]
I think we need to reopen this one. It is clear that this one is a bug, the explanation given by @fartosh in his last comment makes totally sense. Not the entire world relies on ansible-galaxy, so why pretending that you need it? @ssbarnea workaround-ing the problem by using the skiplist can't be an acceptable solution.

**Comment by ssbarnea** [comment]
I am not keen to keep feature requests that nobody is working on as open. While most of the roles I am working on (openstack/opendev ones) are not published to galaxy either I seen nobody declaring that a skiplist is unacceptable. In fact in many places we just added meta.yml file even if it is not published, as it is a very good way to document a role purpose.

As I said on irc, I would support if someone wants to add configuration profiles that can determine set of rules to be enabled or disabled. Still, no need to keep bug open to do that.

A PR would be more than welcomed. Also a feature like this could also address other aspects like preventing failures caused by newly introduced rules, while still allowing to to upgrade the linter to fix existing bugs.

**Comment by rascasoft** [comment]
@ssbarnea we're talking about a specific problem, not a general one: the linter should not pretend the existence of galaxy_info, because it is not requested by the best-practice in the documentation. So the bug is real and should be reopened.
Note that a potential solution could also be to change the doc so that it says you need to provide galaxy_info, but this doesn't change the fact that this problem should be solved in one way or another.

**Comment by ssbarnea** [comment]
Maybe is time to open Pandora's box. Read https://github.com/ansible/ansible/issues/66474

Keep in mind that while ansible-lint is a community project, it is overseen by Ansible Galaxy team and not Ansible Core team. You can read the #ansible-devel irc logs to get an insight about the kind of love the project got from core side. 

While I am not part of any of the teams, I do understand why the main concern is to keep the linter happy with Galaxy team usage. Most of the time I do not need galaxy part either but I learnt to accept the skips as a reasonable compromise.

Regarding documentation best practices, take them with a pinch of salt (and other condiments). Lots of them are outdated, in progress of being updated or not.

Maybe you are not aware but 9/10 practices originate not from core team but from outside world: blogs, articles, discussions and the linter itself.

I tried to convince Ansible core team to lint the examples in order not to teach bad practices and I failed. Even adding "name" to tasks was refused on the claim that it would make the examples more verbose.

If you think this must/can be fixed, I would recommend you to escalate it on #ansible-docs, Ansible Community or even on [r/ansible](https://www.reddit.com/r/ansible/). The best part is that I observed that the team does react to user requests, especially when they are well backed.

**Comment by matkoniecz** [comment]
> I don't see the bug here, all the roles must have meta.

Is there any point at all in adding `galaxy_info` if I am not using Ansible Galaxy at all? I tried using this linter, and it produced plenty of seemingly spurious errors, like this one.

**Comment by phospi** [comment]
I totally agree with @ssbarnea. The naming `galaxy_info` is confusing. It is not the sole purpose of `galaxy_info` to interact with ansible galaxy. The main purpose of `galaxy_info` is to provide meta info. It is good coding practice to provide meta info to your code. If you don't want to do it, use skip_list. 

Which place do you use elsewhere to document overview, description, license info and dependencies of your role? An Markdown or Restructured text without any uniform formatting?  That's the content of `galaxy_info` and it helps everyone getting a first grasp of your role.

@rascasoft Using skip_list is not a workaround. It's the purpose of a skip_list to kick out rules you don't need or like. 

@fartosh I cannot follow your statement that `meta/` is not recommended in ansible docs. The link you're referring to does not endorse any directory. This doc cannot be used as a guide for best-practice.

**Comment by rascasoft** [comment]
@phospi I think I explained my reasons above, and a lot of users agree on the fact that this linter call is misleading. More than this: if we can't rely on the docs that @fartosh mentions, where else do we have to look? Both you and @ssbarnea can insist as much as you want about using `skip_list`, but it is NOT AT ALL what we're saying here.
Facts are that:
- if you don't have a meta directory the ansible linter doesn't bother (so we can assume meta ARE NOT requested);
- if you have meta a role, then the `galaxy_info` file IS requested, but how this can possibly be right if there's no even a single mention of Ansible Galaxy inside the official documentation?

So, let's focus on the facts here and try to find out a solution:
- we do not check for `galaxy_info`;
- we mention the need for `galaxy_info` in the docs;

The least one is wrong because the name itself is confusing: what if I don't want to make my roles use Ansible Galaxy?

**Comment by matkoniecz** [comment]
> Using skip_list is not a workaround. It's the purpose of a skip_list to kick out rules you don't need or like.

On the other hand I would expect sane defaults, not something that requires endless fiddling to be actually useful.

I am especially confused why some of my roles claim to need this thing and some not.

> license info

license goes into machine readable COPYING in root of repository, copying it into every role would be violation of DRY. I would consider encouraging Frankenstein where different part have different licenses as a poor idea

> description

It is in the name

> overview

Nowhere? Why I would even write about such role

`ansible restore/roles/python_package_uploading/tasks/tasks/meta.yml`

```
---
  dependencies:
    - role: python
```

`ansible restore/roles/python_package_uploading/tasks/tasks/main.yml`

```
---
- name: Install twine
  pip:
    name: twine

```

> dependencies

There are no dependencies, except ansible itself.

And for dependencies in roles, it is already specified in meta, right?

Note: I am an Ansible beginner and it is likely that I am wrong/confused. That is why I used `ansible-linter` but just become more confused for now. Unlike say Rubocop where I disagree with many decisions, but it is at least clear what and why they want to achieve.

**Comment by awcrosby** [comment]
As far as what https://galaxy.ansible.com needs regarding metadata, the site uses the 700-level rules to fail import for certain missing metadata. 

For a user who creates local roles, using metadata or not is up to them. I agree with others it is a good practice to include metadata, and `ansible-lint` warns when no metadata is found.

IMO I felt that since the docs [Role Directory Structure](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#id2) mentioned `meta/main.yml`, and that `ansible-galaxy role init <role_name>` auto-creates default metadata, that it implied it is a good practice to include metadata. But maybe the docs could simply say it is a good practice to include metadata with content.

@matkoniecz I recommend using `ansible-galaxy role init <role_name>` to get default metadata and overall directory tree.
