### ISSUE TITLE
Print violation description in output

### ISSUE THREAD

**Issue by nre-ableton** [ansible/ansible-lint#965]
##### Summary

I find ansible-lint's output to be difficult to work with. In order to fix violations, I need to have two terminal windows open: one with `ansible-lint -L | less` and the other with the output of `ansible-lint` itself. I really wish that ansible-lint had an option to print out the violation summary in the output, so I wouldn't need to keep flipping back-and-forth between windows to look up the codes.

Apologies if this has been discussed before, I did a few searches of this project's issues and also manually scanned over currently open issues and didn't see anything. Also, apologies if I am missing something very obvious like a CLI switch which would provide this data. 😅 

##### Issue Type

- Feature Idea

**Comment by ssbarnea** [comment]
I agree with that needs to be done but changing default output of `-L` is problematic as we do not want to lose ability to have a summary of all rules.

I also think that it is not of much usefulness to dump all details about rules, some will soon have quite long descriptions with reasoning, examples and workarounds in them.

How about displaying details of a single rule when the rule id is mentioned like `ansible -L 106` -- if doable with argparse.

Other ideas? The problem here is deciding the CLI API to use, implementation would be quite easy after.

**Comment by nre-ableton** [comment]
Sorry, please forgive the noise on this issue. I didn't realize that the `quiet` switch was active in our `ansible-lint.cfg`, and that this suppressed the rule description in ansible-lint's output. 😅
